package main

import (
	"fmt"
	"log"
	"os"

	"ariga.io/atlas/schemahcl"
	"ariga.io/atlas/sql/mysql"
	"ariga.io/atlas/sql/schema"
	"github.com/hashicorp/hcl/v2/hclparse"
	"github.com/zclconf/go-cty/cty"
)

var (
	// inject by ldflags
	BuildVersion   = ""
	BuildRevision  = ""
	BuildTimestamp = ""
)

func main() {
	log.SetPrefix("atlas-hcl-gen-go: ")
	log.SetFlags(0)

	fmt.Println("BuildVersion:", BuildVersion)
	fmt.Println("BuildRevision:", BuildRevision)
	fmt.Println("BuildTimestamp:", BuildTimestamp)

	if err := run(); err != nil {
		log.Fatal(err)
	}
}

func run() error {
	b, err := os.ReadFile("testdata/schema.hcl")
	if err != nil {
		return err
	}

	var s schema.Schema
	ev := mysql.EvalHCL
	if err := hclBytesFunc(ev)(b, &s, nil); err != nil {
		return err
	}
	fmt.Fprintln(os.Stdout, "// Code generated by github.com/ucpr/atlas-hcl-gen-go. DO NOT EDIT.")

	for i := range s.Tables {
		table := s.Tables[i]
		fmt.Printf("%+v\n", table)
		for j := range table.Columns {
			fmt.Printf("  %+v\n", table.Columns[j])
		}
	}
	return nil
}

// original code: https://github.com/ariga/atlas/blob/98bb7b9da852536523121754d19570c506ba69f7/sql/internal/specutil/spec.go#L165...L173
func hclBytesFunc(ev schemahcl.Evaluator) func(b []byte, v any, inp map[string]cty.Value) error {
	return func(b []byte, v any, inp map[string]cty.Value) error {
		parser := hclparse.NewParser()
		if _, diag := parser.ParseHCL(b, ""); diag.HasErrors() {
			return diag
		}
		return ev.Eval(parser, v, inp)
	}
}
