// Code generated by github.com/ucpr/atlas-hcl-gen-go. DO NOT EDIT.
// atlas-hcl-gen-go:
// source: schema.hcl

package model

import "time"

type Profiles struct {
	Nickname *string    `db:"nickname"`
	Age      *int       `db:"age"`
	Verified *bool      `db:"verified"`
	SignedAt *time.Time `db:"signed_at"`
}
