// Code generated by github.com/ucpr/atlas-hcl-gen-go. DO NOT EDIT.
// atlas-hcl-gen-go:
// source: schema.hcl

package model

import "database/sql"

type Profiles struct {
	Nickname sql.NullString `db:"nickname"`
	Age      sql.NullInt64  `db:"age"`
	Verified sql.NullBool   `db:"verified"`
	SignedAt sql.NullTime   `db:"signed_at"`
}
