// Code generated by github.com/ucpr/atlas-hcl-gen-go. DO NOT EDIT.
// atlas-hcl-gen-go:
// source: schema.hcl

package model

import (
	"encoding/json"
	"time"
)

type Users struct {
	Id          string    `db:"id"`
	Email       string    `db:"email"`
	DisplayName string    `db:"display_name"`
	Bio         *string   `db:"bio"`
	IsAdmin     bool      `db:"is_admin"`
	CreatedAt   time.Time `db:"created_at"`
	UpdatedAt   time.Time `db:"updated_at"`
}

type Posts struct {
	Id          any             `db:"id"`
	Title       string          `db:"title"`
	Slug        string          `db:"slug"`
	Status      string          `db:"status"`
	AuthorId    string          `db:"author_id"`
	PublishedAt *time.Time      `db:"published_at"`
	Metadata    json.RawMessage `db:"metadata"`
	Rating      *string         `db:"rating"`
	CoverImage  []byte          `db:"cover_image"`
	CreatedAt   time.Time       `db:"created_at"`
	UpdatedAt   time.Time       `db:"updated_at"`
}

type Comments struct {
	Id        any       `db:"id"`
	PostId    int       `db:"post_id"`
	AuthorId  *string   `db:"author_id"`
	Body      string    `db:"body"`
	CreatedAt time.Time `db:"created_at"`
}

type Tags struct {
	Id   any    `db:"id"`
	Name string `db:"name"`
}

type PostTags struct {
	PostId int `db:"post_id"`
	TagId  int `db:"tag_id"`
}
