// Code generated by github.com/ucpr/atlas-hcl-gen-go. DO NOT EDIT.
// atlas-hcl-gen-go:
// source: schema.hcl

package model

import "math/big"

type Orders struct {
	Amount *big.Rat `db:"amount"`
}
